### ISSUE TITLE
Status update by GPIO14

### ISSUE THREAD

**Issue by gabriuelucho** [manolab/homebridge-sonoff-stateful-blinds#1]
Hello, 

I'm using this plugin and it works quite well, but I would like to use the GPIO14 input to up/down the blinds trough a physical switch.

It works, I can move the blinds with Siri and so on, and also I can move them with the GPIO14 input , but in that case, the status is not updated in the Homekit App.

Is it possible to update the status when I use the GPIO14 input?

Thank you

**Comment by manolab** [comment]
Unfortunately there's no way of knowing where the blind is... One thing I could add is a "re-initialization" on Homebridge restart: the blind would open totally and restored to the last known position before the manual movement. Is that of any interest?

**Comment by gabriuelucho** [comment]
Well that's not exactly what I'm looking for. I can imagine is not possible to know the real position of the blind using only sonoff., but maybe I did not explained properly.

Indeed what I want is that when I use the Gpio14 input (by physical push button), it is also reflected in the Home app.
As is already done, the position could be "calculated" considering the time the button is pressed.

Example:
You send the order of moving 20% up using home app.
Sonoff will calculate how much time needs to activate (lets' say 10 seconds)
Now the position of the blind is 20% opened.
If now I push the button connected to GPIO14 during 10 seconds more, the blind will move to 40% open. What I want is to have these feedback on home app.

It should be possible to count how much time the button is pressed and calculate the actual %... (I have no clue but sounds quite simple ;-) 

I hope now it's more clear

Thanks

**Comment by gabriuelucho** [comment]
> Well that's not exactly what I'm looking for. I can imagine is not possible to know the real position of the blind using only sonoff., but maybe I did not explained properly.
> 
> Indeed what I want is that when I use the Gpio14 input (by physical push button), it is also reflected in the Home app.
> As is already done, the position could be "calculated" considering the time the button is pressed.
> 
> Example:
> You send the order of moving 20% up using home app.
> Sonoff will calculate how much time needs to activate (lets' say 10 seconds)
> Now the position of the blind is 20% opened.
> If now I push the button connected to GPIO14 during 10 seconds more, the blind will move to 40% open. What I want is to have these feedback on home app.
> 
> It should be possible to count how much time the button is pressed and calculate the actual %... (I have no clue but sounds quite simple ;-)
> 
> I hope now it's more clear
> 
> Thanks

Sorry I forgot to say something more, I not sure if I should open a new issue.

I would like to know if it's possible to make a kind of security in the plugin. To be sure that both motors (up & down) are switched on at same time.

I'm using 2 Sonoff Basic, so I thought if it's possible to switch off any sonoff when the first is switched on.

Moving UP:
Switch ON sonoff UP + Switch OFF sonoff Down

Moving DOWN:
Switch ON sonoff DOWN + Switch OFF sonoff UP

Thanks

**Comment by gabriuelucho** [comment]
Thank you for your remarks, I've opened the new issue with the new topic.
